## Introduction to NumPy
- Numpy is a multidimensional array library. Numpy can be used to store data like 1D,2D,3D or 4D arrays.

**Why Numpy?**

- Numpy Arrays are faster than lists as numpy uses fixed type (all data in array is of a singular type).
- Lists contain each element as a full python object with the metadata of the object as well, whereas Numpy doesn't do that and stores only the element
- Numpy vectorizes an operation in arrays(the whole operation is done in one go for the entire array rather than doing it individually.)
- Numpy stores data in a sequence ([data1,data2,...datan]), whereas python lists don't do this.

Now that we have learned a little bit about NumPy and it's advantages, let's learn about NumPy arrays, the building block of NumPy.  

In [1]:
#Firstly we need to import NumPy.
import numpy as np

Let's create our first NumPy array! To achieve this we can use `np.array()` method on any iterable.

In [2]:
nums = [i for i in range(6)]#Python list of numbers from 0-5
nums_array = np.array(nums)
print(nums_array)

[0 1 2 3 4 5]


The array looks same as a python list as it is 1D. So, let's create a 2D NumPy array and see how it differs from the 1D array.

**When creating array of N dimensions, we need to pass N lists in the np.array method inside a tuple/list**

In [3]:
twod_array = np.array([[1,2],[3,4]])

In [4]:
print(twod_array)

[[1 2]
 [3 4]]


# Basic array attributes:
- .ndim &#8594; the number of dimensions(axes) of the array.
- .shape &#8594; dimensions of the array in (m,n) format
- .size &#8594; total number of elements in the array (is equal to the product of elements of .shape)
- .dtype &#8594; type of the elements in array

In [5]:
print(f"Number of dimensions:{twod_array.ndim}")
print(f"Shape of array:{twod_array.shape}")
print(f"Number of elemebts in the array:{twod_array.size}")
print(f"Data type of elements in the array:{twod_array.dtype}")

Number of dimensions:2
Shape of array:(2, 2)
Number of elemebts in the array:4
Data type of elements in the array:int64


# Array Creation:
We saw how to create numpy arrays with python iterables, now let's look at some other ways to create numpy arrays. 

1) `np.zeros()` &#8594; Creates a NumPy array where all the elements are 0.
2) `np.ones()`&#8594; Creates a NumPy array where all the elements are 1.
3) `np.arange()`&#8594; Creates a  NumPy array with numbers in order, separated by a set gap.
4) `np.full()` &#8594; Creates a NumPy array of ndim with the sepcified value.
5) `np.eye()` &#8594; Creates an Identity Matrix of ndim.

Code example for each of the ways is given below:

In [6]:
#np.zeros():
zeros = np.zeros(shape=(4,7),dtype=np.int8)
print(zeros)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [7]:
#np.ones():
ones = np.ones(shape=(4,7),dtype=np.int8)
print(ones)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [8]:
#np.arange():
arange = np.arange(4,7,0.6)#follows the format (start,stop,step)
print(arange)

[4.  4.6 5.2 5.8 6.4]


In [9]:
#np.full()
full = np.full(shape=(2,2),fill_value=8)
print(full)

[[8 8]
 [8 8]]


In [10]:
#np.eye()
identity = np.eye(3,5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Indexing, Slicing and Boolean indexing in NumPy

- Basic indexing  is quite similar to how indexing concepts work for python lists.
- Slicing is also very similar to python list slicing.
- Boolean indexing is using certain conditions in the indexes themselves to get certain parts of the Array.


In [11]:
#Basic indexing:
array = np.array([[1,2,3],[4,5,6]])
print(array[1])#Prints the list provided in the .array() method in the 1st index.([4,5,6] in this case)
print(array[1,2]) #Prints the element in the 2 index of the list in 1 index of the array.
print(array[-1,-2]) #Prints the  element in -2 position of the list in the -1 index of array.

[4 5 6]
6
5


- Reversing a NumPy array:
    - To reverse a NumPy array, we can either user the `np.flip()` method or use the notation `array[::-1]`, using np.flip() also flips the elements inside the array whereas using the notation only flips the array itself. 

In [12]:
print(np.flip(array))

[[6 5 4]
 [3 2 1]]


In [13]:
print(array[::-1])

[[4 5 6]
 [1 2 3]]


# Slicing:
- As mentioned previously, slicing NumPy arrays is very similar to slicing python lists. Let's quickly go over slicing NumPy arrays.
- Similar to lists in python , NumPy arrays follow the `[start:stop:step]` format, where start is inclusive (the element in the provided index is included in the output) and stop is exclusive (the element in the provided index is excluded in the output) and step is simply the number of elements to skip in an array.  

In [14]:
slicing_array = np.array([i for i in range(10)])

In [15]:
print(slicing_array[2:5]) # Prints elements from index 2-5 (exclusively)
print(slicing_array[::2]) # Printing elements from the array with the step of 2. It stops at the last possible index when no start or step is defined/given. Basically prints every second element.
print(slicing_array[1:])  # Prints elements from the first index (inclusively) to the end of the array as it is not specified.

[2 3 4]
[0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]


In [16]:
print(slicing_array[-3:])#Prints elements from the 3rd element from the back 
print(slicing_array[::-1])#Prints elements from the last element (reverse order)

[7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [17]:
print(slicing_array[None,:]) # Converts array into a row vector (2D array)
print(slicing_array[:,None]) # Conversts array into a column vecotr (2D array)

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Slicing in 2D arrays

In [18]:
slicing_array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(slicing_array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- In 2D arrays, slicing works in a similar way but it takes the row and columns. It follows the format `array[row_start:row_stop:row_step,column_start:column_stop:column_step]`.

row_start,column_start &#8594; inclusive

row_stop,column_stop &#8594; exclusive

In [19]:
print(slicing_array_2d[0:2,1:3]) #Slices the array from 0->2 row wise and 1->3 column wise.

[[2 3]
 [5 6]]


In [20]:
print(slicing_array_2d[0:3:2,1:4:2]) #Slices the array from 0->3 with a step of 2  row wise and 1->4 with a step of 2.


[[2]
 [8]]


In [22]:
print(slicing_array_2d[-2:,:-1])#Slices last two rows excluding the last column

[[4 5]
 [7 8]]


In [23]:
#Reversing a 2D array
print(slicing_array_2d[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


# Boolean Indexing:
- Boolean indexing allows us to filter elements based on the defined condition. These conditions are defined with `boolean masks`. Boolean masks are NumPy arrays containing the truth values (True/False) that corespond to each element in the array based on the condition.

In [28]:
arr = np.array([i for i in range(1,10)])
boolean_mask = arr>2

In [29]:
print(boolean_mask)#This is the intermediate output in boolean indexing.

[False False  True  True  True  True  True  True  True]


In the above example we can see how each element of the `boolean_mask` corresponds to either True of False based on the condition of `arr>2`. This is similar to using conditions in a python list as shown below.

In [50]:
#Boolean indexing in lists

numbers = [i for i in range(1,10)]
masked_list = [number>2 for number in numbers]
print(masked_list)

[False, False, True, True, True, True, True, True, True]


In [36]:
#Applying the boolean mask/ using boolean indexing:
print(arr[boolean_mask])

[3 4 5 6 7 8 9]


So, in short, We can apply conditions to all elements of a numpy array directly through the array itself rather than having to use loops like in python lists. This is called Boolean Indexing. Now, let's take a look at boolean indexings in 2D arrays, which is very much similar to the use of boolean indexing in 1D arrays.

In [37]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
boolean_mask_2d = arr_2d % 2 == 0

In [39]:
print(boolean_mask_2d) #Intermediate output

[[False  True False]
 [ True False  True]
 [False  True False]]


In [49]:
#using the same condition in python lists:
list_2d = [[1,2,3],[4,5,6],[7,8,9]]

boolean_mask_2d = [[elem % 2 == 0 for elem in nested_list] for nested_list in list_2d]
print(boolean_mask_2d)


[[False, True, False], [True, False, True], [False, True, False]]


In [52]:
print(arr_2d[boolean_mask_2d]) # Applying boolean mask

[2 4 6 8]


# Operations in NumPy arrays:
- In this topic, we will look at the basic,mathematical,reshaping,transposing,broadcasting and aggregation operations.